mongo:
  image: mongo:latest
  ports:
   - "27017:27017"
server:
  build: .
  ports:
   - "8080:8080"
  links:
   - mongo
  environment:
   - QUIET_MONGO_URI=mongo
   - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}