'use strict';

module.exports = {
  // Error
  E_DATABASE: 101,
  E_UNKNOWN_USER: 102,
  E_INCORRECT_TOKEN: 103,
  E_INVALID_PARAM: 104,

  // Success
  S_PHONE_CREATED: 201,
  S_USER_CREATED: 202,
  S_PHONE_FOUND: 203,
  S_USER_FOUND: 204,
  S_PHONE_REPORTED: 205,
  S_TOKEN_VALIDATED: 206,
  S_DATABASE_CONNECTED: 207,
  S_DATABASE_CONNECTION_RETRIEVED: 208,
};
