'use strict';

module.exports = {
  // Error
  E_DATABASE: 101,
  E_UNKNOWN_USER: 102,
  E_INCORRECT_TOKEN: 103,

  // Success
  S_CREATED: 201,
  S_FOUND: 202,
  S_REPORTED: 203,
  S_TOKEN_VALIDATED: 204,
  S_DATABASE_CONNECTED: 205,
  S_DATABASE_CONNECTION_RETRIEVED: 206,
};
